name: Test

on:
  pull_request:
    branches:
      - main

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install .
          pip install pytest pytest-asyncio

      - name: Run tests
        run: pytest
